apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wordpress-integration-updater
spec:
  schedule: "24 */3 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wordpress-integration-updater
            image: nateinaction/wordpress-integration-updater
            volumeMounts:
            - name: "secrets"
              mountPath: "/secrets"
              readOnly: true
          volumes:
          - name: secrets
            secret:
              secretName: github-app-key-pem
          restartPolicy: OnFailure